# -*- coding: utf-8 -*-
"""PLC_Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eg98MwJIatR_PBwvFuDZPlEq6wcOEbgh
"""

#!git clone  https://github.com/G-gabry/PLC.git

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import librosa
# import IPython.display as ipd  # Colab-only, not installed locally, unused in this file
import time as time_module
import os
import scipy.signal
import scipy.linalg
import soundfile as sf
from numba import njit

BASE_DIR = Path(r'C:\Users\g\PLC\PLC_NN\2024-music-plc-challenge\parcnet-is2\example_test_set')
LOSSY_DIR = BASE_DIR / 'lossy'
TRACES_DIR = BASE_DIR / 'traces'
ENHANCED_DIR = BASE_DIR / 'enhanced'
ENHANCED_AR_ONLY_DIR = BASE_DIR / 'enhanced_ar_only'
FIGURES_DIR = Path(r'C:\Users\g\PLC\PLC_NN\2024-music-plc-challenge\plc_test_figures')
FIGURES_DIR.mkdir(exist_ok=True, parents=True)
PACKET_SIZE = 512
LPC_DIAGONAL_LOAD = 0.001

def Calculate_brust_lengths(sequence):
    left=0
    brust_lengths=[]
    for right in range(len(sequence)):
        if sequence[right]==0:
           if sequence[left]==1:
             brust_lengths.append(right-left)
           left=right+1
    if left<len(sequence) and sequence[left]==1:
       brust_lengths.append(len(sequence)-left)
    return brust_lengths

def calculate_markov_transitions(sequence):
    """
    Calculates the transition probabilities for the Gilbert-Elliott model.
    Simple Version: We manually count every time the state changes.
    """
    if len(sequence) < 2:
        return 0.0, 0.0

    count_0_to_0 = 0
    count_0_to_1 = 0
    count_1_to_0 = 0
    count_1_to_1 = 0


    for i in range(len(sequence) - 1):
        current_packet = sequence[i]
        next_packet = sequence[i+1]

        if current_packet == 0:
            if next_packet == 0:
                count_0_to_0 += 1
            else:
                count_0_to_1 += 1
        else:
            if next_packet == 0:
                count_1_to_0 += 1
            else:
                count_1_to_1 += 1

    total_starts_at_0 = count_0_to_0 + count_0_to_1
    total_starts_at_1 = count_1_to_0 + count_1_to_1

    p01 = count_0_to_1 / total_starts_at_0 if total_starts_at_0 > 0 else 0.0
    p11 = count_1_to_1 / total_starts_at_1 if total_starts_at_1 > 0 else 0.0

    return p01, p11

def run_network_analysis(folder_path):
    path = Path(folder_path)

    # 1. Gather files
    trace_files = []
    for file in os.listdir(path):
        if file.endswith(".txt"):
            trace_files.append(path / file)


    all_packets = []
    all_bursts = []
    micro_stats = []

    # 2. Process each file one by one
    for f in trace_files:

            data = np.loadtxt(f, dtype=int).flatten()

            if len(data) == 0:
                continue


            file_plr = np.mean(data)
            micro_stats.append({
                'filename': f.name,
                'packet_loss_rate': file_plr
            })

            # We add every packet found into one giant list for global stats
            all_packets.extend(data)

            # We find the bursts for this specific file and add them to our list
            file_bursts = Calculate_brust_lengths(data)
            all_bursts.extend(file_bursts)




    # 3. Calculate Global Statistics
    combined_sequence = np.array(all_packets)
    plr = np.mean(combined_sequence)
    p01, p11 = calculate_markov_transitions(combined_sequence)

    print("\n--- Global Network Statistics ---")
    print(f"Overall Packet Loss Rate (PLR): {plr * 100:.2f}%")
    print(f"Transition Prob P(0->1)      : {p01:.4f}")
    print(f"Transition Prob P(1->1)      : {p11:.4f}")

    if all_bursts:
        print(f"Average Loss Burst Length     : {np.mean(all_bursts):.2f} packets")

    #Return BOTH the burst list and the micro_stats list
    return all_bursts, micro_stats

all_bursts, micro_stats = run_network_analysis(TRACES_DIR)

# Make sure we actually found data before trying to plot
if all_bursts and micro_stats:
    # Convert the per-file dictionary list into a Pandas DataFrame for Plot 2
    df_micro = pd.DataFrame(micro_stats)
    print(df_micro.head())
    sns.set_theme(style="whitegrid")
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # Plot 1: Global Burst Length Distribution (Log Scale)
    sns.histplot(all_bursts, bins=range(1, max(all_bursts) + 2),
                 discrete=True, ax=ax1, color="#2ecc71")
    ax1.set_yscale('log')
    ax1.set_title('Global Burst Length Distribution', fontsize=14, pad=15)
    ax1.set_xlabel('Consecutive Packets Lost (Burst Length)', fontsize=12)
    ax1.set_ylabel('Count (Log Scale)', fontsize=12)
    ax1.set_xticks(range(1, max(all_bursts) + 1))

    # Plot 2: Per-File Packet Loss Rate Variance
    sns.histplot(data=df_micro, x='packet_loss_rate', bins=20, ax=ax2, color="#e74c3c")
    ax2.set_title('Distribution of Packet Loss Rates Across Files', fontsize=14, pad=15)
    ax2.set_xlabel('Average Packet Loss Rate per File', fontsize=12)
    ax2.set_ylabel('Density', fontsize=12)

    # Add a vertical line showing the global average
    global_avg = df_micro['packet_loss_rate'].mean()
    ax2.axvline(global_avg, color='black', linestyle='--', label=f'Global Avg ({global_avg*100:.1f}%)')
    ax2.legend()

    plt.tight_layout()
    fig.savefig(FIGURES_DIR / "network_statistics.png", dpi=150, bbox_inches='tight')
    plt.show()

@njit
def _parcnet_predict_loop(past: np.ndarray, coeff: np.ndarray, steps: int) -> np.ndarray:
    prediction = np.zeros(steps)
    for i in range(steps):
        pred = np.dot(past, coeff)
        prediction[i] = pred
        past = np.roll(past, -1)
        past[-1] = pred
    return prediction


class ARModel:
    """AR(order) linear predictor -- same fit + predict as PARCnet's ar_model.py."""

    def __init__(self, order, diagonal_load=0.001):
        self.order = order
        self.diagonal_load = diagonal_load

    def fit(self, past_audio):
        acf = scipy.signal.correlate(past_audio, past_audio, mode='full')
        if np.any(np.isnan(acf)):
            acf = scipy.signal.correlate(past_audio, past_audio, mode='full', method='direct')

        zero_lag = len(acf) // 2
        c = acf[zero_lag:zero_lag + self.order].copy()
        c[0] += self.diagonal_load
        b = acf[zero_lag + 1:zero_lag + self.order + 1]
        return scipy.linalg.solve_toeplitz(c, b, check_finite=False)

    def predict(self, past_audio, steps):
        coeff = self.fit(past_audio)
        past_view = np.ascontiguousarray(past_audio[-self.order:], dtype=np.float32)
        coeff_view = np.ascontiguousarray(coeff[::-1], dtype=np.float32)
        pred = _parcnet_predict_loop(past=past_view, coeff=coeff_view, steps=steps)

        if np.any(np.isnan(pred)) or np.any(np.abs(pred) > 1.5):
            return np.zeros(steps)
        return pred

class LPCConcealer:
    """Packet-loss concealment with AR/LPC only -- PARCnet's own per-packet loop, minus the neural network."""

    def __init__(self, order, diagonal_load, packet_size, extra_dim, context_dim, equal_power=True):
        self.ar_model = ARModel(order, diagonal_load)
        self.packet_size = packet_size
        self.extra_dim = extra_dim
        self.context_dim = context_dim
        self.pred_dim = packet_size + extra_dim

        if extra_dim > 0:
            linear = np.linspace(0., 1., extra_dim)
            self.fade_in = np.sqrt(linear) if equal_power else linear
            self.fade_out = np.sqrt(1. - linear) if equal_power else 1. - linear

    def __call__(self, audio, trace):
        output = np.pad(audio.copy(), (0, self.extra_dim))
        is_burst = False

        for i, lost in enumerate(trace):
            if not lost:
                is_burst = False
                continue

            idx = i * self.packet_size
            valid = output[max(0, idx - self.context_dim):idx]
            valid = np.pad(valid, (self.context_dim - len(valid), 0))
            prediction = self.ar_model.predict(valid, self.pred_dim)

            if self.extra_dim > 0:
                prediction[-self.extra_dim:] *= self.fade_out
                if is_burst:
                    prediction[:self.extra_dim] *= self.fade_in
                output[idx + self.packet_size:idx + self.pred_dim] *= self.fade_in

            output[idx:idx + self.pred_dim] += prediction
            is_burst = True

        return output[:len(audio)]

def compare_all_methods(filename_base, start_packet_idx, burst_len_packets,
                         order=256, diagonal_load=0.001, context_dim=4096, extra_dim=256,
                         equal_power=False, context_ms=40, example_num=1):
    """
    Compares 4 PLC methods on the same real burst: this notebook's own LPCConcealer
    ("this LPC"), PARCnet's real pipeline with the neural network zeroed out ("LPC
    without NN", loaded from ENHANCED_AR_ONLY_DIR), a single one-shot AR call with no
    fades ("LPC class"), and PARCnet's real pipeline with the neural network ("LPC with
    NN", loaded from ENHANCED_DIR). Defaults match PARCnet's own order/diagonal_load/
    context_dim/extra_dim, so out of the box every method is on equal footing and
    differences reflect the algorithm, not mismatched settings. Prints the MSE between
    every pair over the gap itself (not the surrounding context) and returns it.
    """
    lossy, sr = librosa.load(LOSSY_DIR / f'{filename_base}.wav', sr=None)
    trace = np.loadtxt(TRACES_DIR / f'{filename_base}.txt', dtype=int).flatten()
    enhanced, _ = librosa.load(ENHANCED_DIR / f'{filename_base}.wav', sr=None)
    enhanced_ar_only, _ = librosa.load(ENHANCED_AR_ONLY_DIR / f'{filename_base}.wav', sr=None)

    concealer = LPCConcealer(order, diagonal_load, PACKET_SIZE, extra_dim, context_dim, equal_power)
    this_lpc = concealer(lossy, trace)

    gap_start = start_packet_idx * PACKET_SIZE
    gap_size = burst_len_packets * PACKET_SIZE
    gap_end = gap_start + gap_size
    valid = lossy[max(0, gap_start - context_dim):gap_start]
    valid = np.pad(valid, (context_dim - len(valid), 0))
    # lpc_class = lossy.copy()
    # lpc_class[gap_start:gap_end] = ARModel(order, diagonal_load).predict(valid, gap_size)

    signals = [
        ("this_lpc",       "This LPC (recursive)",      this_lpc,         "#2a78d6"),
        ("lpc_without_nn", "LPC without NN (pipeline)", enhanced_ar_only, "#e8871e"),
        # ("lpc_class",      "LPC class (one-shot)",      lpc_class,        "#7d5ba6"),
        ("lpc_with_nn",    "LPC with NN (PARCnet)",     enhanced,         "#1baf7a"),
    ]

    context = int(sr * context_ms / 1000)
    win_start = max(0, gap_start - context)
    win_end = min(len(lossy), gap_end + context)
    t_ms = (np.arange(win_start, win_end) - gap_start) / sr * 1000
    gap_end_ms = gap_size / sr * 1000
    y_max = max(np.max(np.abs(sig[win_start:win_end])) for _, _, sig, _ in signals) * 1.1

    fig, axes = plt.subplots(2, 4, figsize=(18, 8), gridspec_kw={"height_ratios": [1, 1.15]})

    for col, (_, label, sig, color) in enumerate(signals):
        ax = axes[0, col]
        ax.plot(t_ms, sig[win_start:win_end], color=color, linewidth=1.1)
        ax.axvspan(0, gap_end_ms, color="black", alpha=0.08)
        ax.set_title(label, fontsize=10, color=color)
        ax.set_ylim(-y_max, y_max)
        ax.set_xlabel("Time relative to gap start (ms)")
        if col == 0:
            ax.set_ylabel("Amplitude")

    specs_db = {}
    for name, _, sig, _ in signals:
        stft = librosa.stft(sig[win_start:win_end], n_fft=1024, hop_length=64)
        specs_db[name] = librosa.amplitude_to_db(np.abs(stft), ref=np.max)
    vmin = min(s.min() for s in specs_db.values())
    vmax = max(s.max() for s in specs_db.values())

    for col, (name, label, _, color) in enumerate(signals):
        ax = axes[1, col]
        img = librosa.display.specshow(specs_db[name], sr=sr, hop_length=64, x_axis="time", y_axis="hz",
                                        ax=ax, cmap="magma", vmin=vmin, vmax=vmax)
        ax.set_title(f"Spectrogram — {label}", fontsize=9, color=color)
        ax.set_ylim(0, 8000)
        ax.set_xlabel("Time (s)")
        if col == 0:
            ax.set_ylabel("Frequency (Hz)")

    fig.colorbar(img, ax=axes[1, :], format="%+2.0f dB", fraction=0.02, pad=0.02, label="Magnitude (dB)")
    fig.suptitle(f"{filename_base} — {burst_len_packets}-packet burst, example {example_num}", fontsize=13, y=1.0)
    fig.savefig(FIGURES_DIR / f"compare_{filename_base}_{burst_len_packets}pkt_ex{example_num}.png",
                dpi=150, bbox_inches='tight')
    plt.show()

    diff_pairs = [(i, j) for i in range(len(signals)) for j in range(i + 1, len(signals))]
    diffs = [signals[i][2][win_start:win_end] - signals[j][2][win_start:win_end] for i, j in diff_pairs]
    diff_y_max = max(np.max(np.abs(d)) for d in diffs) * 1.1

    diff_fig, diff_axes = plt.subplots(2, 3, figsize=(15, 7))
    rows = []
    for ax, (i, j), diff in zip(diff_axes.flat, diff_pairs, diffs):
        name_a, label_a, sig_a, _ = signals[i]
        name_b, label_b, sig_b, _ = signals[j]
        gap_mse = np.mean((sig_a[gap_start:gap_end] - sig_b[gap_start:gap_end]) ** 2)
        rows.append({'pair': f'{name_a} vs {name_b}', 'gap_mse': gap_mse})

        ax.plot(t_ms, diff, color="#7d5ba6", linewidth=1.0)
        ax.axvspan(0, gap_end_ms, color="black", alpha=0.08)
        ax.set_title(f"{label_a} minus {label_b}\nGap MSE: {gap_mse:.3e}", fontsize=9)
        ax.set_ylim(-diff_y_max, diff_y_max)
        ax.set_xlabel("Time relative to gap start (ms)")

    diff_fig.suptitle(f"{filename_base} — pairwise differences, {burst_len_packets}-packet burst, example {example_num}",
                       fontsize=12, y=1.02)
    diff_fig.tight_layout()
    diff_fig.savefig(FIGURES_DIR / f"diff_{filename_base}_{burst_len_packets}pkt_ex{example_num}.png",
                      dpi=150, bbox_inches='tight')
    plt.show()

    mse_table = pd.DataFrame(rows)
    print(mse_table.to_string(index=False))
    return mse_table

def extract_bursts(sequence):
    """
    Extracts (start_packet_idx, burst_length) for all bursts (consecutive '1's) in a sequence.
    """
    bursts = []
    i = 0
    while i < len(sequence):
        if sequence[i] == 1:
            start_idx = i
            length = 0
            while i < len(sequence) and sequence[i] == 1:
                length += 1
                i += 1
            bursts.append((start_idx, length))
        else:
            i += 1
    return bursts

def detect_burst_lengths_in_files(filenames):
    """
    Finds all unique burst lengths that actually happened in the specified files
    and returns them in a sorted list.
    """
    all_burst_lengths = set()
    burst_examples_dict = {} # Dictionary to store examples: {burst_len: [(filename_base, start_idx), ...]}

    for name in filenames:
        trace_path = TRACES_DIR / f"{name}.txt"
        if not trace_path.exists():
            print(f"Warning: Trace file not found at {trace_path}")
            continue

        data = np.loadtxt(trace_path, dtype=int).flatten()
        if len(data) == 0:
            continue

        file_bursts = extract_bursts(data) # Use the newly defined extract_bursts
        for start_idx, length in file_bursts:
            all_burst_lengths.add(length)
            if length not in burst_examples_dict:
                burst_examples_dict[length] = []
            # Store up to 3 examples per burst length to avoid too many plots
            if len(burst_examples_dict[length]) < 3:
                burst_examples_dict[length].append((name, start_idx))

    return sorted(list(all_burst_lengths)), burst_examples_dict

def analyze_and_plot_repairs(order=256, diagonal_load=0.001, context_dim=4096, extra_dim=256,
                              equal_power=False, filenames=None, custom_targets=None, examples_per_target=1):
    """Detects real bursts (or uses custom_targets) and runs compare_all_methods on each."""
    targets = []
    burst_examples = {} # Initialize burst_examples

    if custom_targets is not None:
        targets = custom_targets
        print(f"Using provided custom targets: {targets}")
        # Need to populate burst_examples for custom targets.
        # We'll detect from all files and then filter for the custom targets.
        all_trace_files_names = [f.stem for f in TRACES_DIR.iterdir() if f.suffix == '.txt']
        _, all_burst_examples_from_dataset = detect_burst_lengths_in_files(all_trace_files_names)

        for target_len in targets:
            if target_len in all_burst_examples_from_dataset:
                burst_examples[target_len] = all_burst_examples_from_dataset[target_len][:examples_per_target]
            else:
                burst_examples[target_len] = []
        if not any(burst_examples.values()):
            print("Warning: No examples found for custom targets. Check filenames or target lengths.")

    elif filenames is not None:
        targets, detected_burst_examples = detect_burst_lengths_in_files(filenames)
        # Filter detected_burst_examples to keep only 'examples_per_target'
        for b_len in targets:
            burst_examples[b_len] = detected_burst_examples[b_len][:examples_per_target]
        print(f"Auto-detected burst lengths in {filenames}: {targets}")

    else:
        # Default behavior: detect from all files
        all_trace_files_names = [f.stem for f in TRACES_DIR.iterdir() if f.suffix == '.txt']
        detected_targets, detected_burst_examples = detect_burst_lengths_in_files(all_trace_files_names)

        # Override detected targets with default values
        targets = [1, 4, 8, 16]
        print(f"Using default target burst lengths: {targets}")

        # Populate burst_examples only for the default targets, taking a few examples
        for target_len in targets:
            if target_len in detected_burst_examples:
                burst_examples[target_len] = detected_burst_examples[target_len][:examples_per_target]
            else:
                burst_examples[target_len] = []


    # 4. Generate the audio repair waveforms for each target
    if not targets:
        print("No target burst lengths to analyze.")
        return

    for burst_len in targets:
        examples = burst_examples.get(burst_len, [])

        if not examples:
            scope = f"in {filenames}" if filenames else "in the dataset"
            print(f"\nNo {burst_len}-packet burst found {scope}.")
            continue # Skip to the next burst length

        for example_num, (filename_base, start_packet_idx) in enumerate(examples, start=1):
            print(f"\n--- BURST LENGTH: {burst_len} PACKETS ({filename_base}), example {example_num} ---")
            compare_all_methods(filename_base, start_packet_idx, burst_len,
                                 order=order, diagonal_load=diagonal_load,
                                 context_dim=context_dim, extra_dim=extra_dim,
                                 equal_power=equal_power, example_num=example_num)

analyze_and_plot_repairs(
    filenames=['1UaHCp-394-87506-140741-186260-68344-3434-1214'],
    custom_targets=[2, 4, 16],
)

def analyze_custom_lpc_sweep(list_of_coefficients, list_of_previous_samples, file_index=0):
    """
    Sweeps custom, explicit lists of LPC orders and context window lengths,
    timing the fit and plotting a single combined heatmap.
    """
    lossy_files = sorted(LOSSY_DIR.glob("*.wav"))
    audio, sr = librosa.load(lossy_files[file_index], sr=None, mono=True)

    max_prev_samples = max(list_of_previous_samples)
    max_order = max(list_of_coefficients)

    # Ensure the audio file is long enough for the largest test
    if len(audio) < max_prev_samples:
        raise ValueError(f"{lossy_files[file_index].name} has only {len(audio)} samples, "
                         f"need at least {max_prev_samples}")

    # Anchor the start position so every test analyzes the exact same acoustic event
    start_pos = max_prev_samples

    # Initialize the results grid matching the dimensions of your custom lists
    timing_ms = np.full((len(list_of_previous_samples), len(list_of_coefficients)), np.nan)

    # Warm-up the solver to absorb initialization latency
    print("Warming up the linear solver...")
    _ = ARModel(max_order, LPC_DIAGONAL_LOAD).fit(audio[:max_order*2])

    print(f"Running custom matrix sweep on {lossy_files[file_index].name}...")

    # The Dual Loop: Exactly mapping your specific arrays
    for i, n_prev in enumerate(list_of_previous_samples):
        clue = audio[start_pos - n_prev : start_pos]

        for j, order in enumerate(list_of_coefficients):
            if order >= n_prev:
                continue  # Skip mathematically invalid combinations

            # --- TIMER ---
            t0 = time_module.perf_counter()
            _ = ARModel(order, LPC_DIAGONAL_LOAD).fit(clue)
            timing_ms[i, j] = (time_module.perf_counter() - t0) * 1000

    # --- PLOTTING THE HEATMAP ---
    fig, ax = plt.subplots(figsize=(9, 7))
    ax.set_facecolor("lightgrey") # Highlights invalid (NaN) regions

    img = ax.imshow(timing_ms, origin="lower", cmap="magma", aspect="auto")

    # Force the X and Y axes to strictly display the numbers from your custom lists
    ax.set_xticks(range(len(list_of_coefficients)))
    ax.set_xticklabels(list_of_coefficients)
    ax.set_yticks(range(len(list_of_previous_samples)))
    ax.set_yticklabels(list_of_previous_samples)

    ax.set_xlabel("Number of coefficients (LPC order)")
    ax.set_ylabel("Number of previous samples (context window)")
    ax.set_title(f"LPC fit time (ms) — Custom Sweep")

    # Dynamic text color to ensure readability against the magma color scale
    max_time = np.nanmax(timing_ms)
    for i in range(len(list_of_previous_samples)):
        for j in range(len(list_of_coefficients)):
            val = timing_ms[i, j]
            if not np.isnan(val):
                t_color = "black" if val > (max_time * 0.7) else "white"
                ax.text(j, i, f"{val:.1f}", ha="center", va="center", fontsize=8, color=t_color)

    fig.colorbar(img, ax=ax, label="Fit time (ms)")
    fig.savefig(FIGURES_DIR / "lpc_sweep_heatmap.png", dpi=150, bbox_inches='tight')

    plt.show()

    return timing_ms

# Define your exact target variables
list_of_coefficients = [256, 320, 400, 480]
list_of_previous_samples = [512, 1024, 1536, 1900]

# Generate the unified heatmap
timing_results = analyze_custom_lpc_sweep(
    list_of_coefficients=list_of_coefficients,
    list_of_previous_samples=list_of_previous_samples,
    file_index=0
)